### ISSUE TITLE
Containers should share their pacman cache

### ISSUE THREAD

**Issue by f-breidenstein** [aurblobs/aurblobs#12]
Idea:

- User triggers "update repo"
- Create `/foo/bar` folder on host (tempdir)
- Mount `/foo/bar` inside the container as `/var/cache/pacman/pkg`
- Update all available packages in the packages.json
- Remove `/foo/bar` after update is done

This way all container can share a common pkg cache for pacman which will save some time and bandwidth for the cost of some storage space.

**Comment by mweinelt** [comment]
Related:
>         warning: no /var/cache/pacman/pkg/ cache exists, creating...
